#!/usr/bin/env escript
-module(runnifty).
-export([main/1]).

generate_files(HeaderName, ModuleName, Options) ->
	case nifty:generate(HeaderName, ModuleName, Options, filename:dirname(escript:script_name()), false) of
		fail -> fail;
		{EOutput, COutput} ->
			ok = file:write_file(ModuleName++"_nif.c", io_lib:fwrite("~s", [COutput])),
			ok = file:write_file(ModuleName++".erl", io_lib:fwrite("~s", [EOutput]))
	end.

main([Header, Module| Options]) ->
    true = code:add_pathz(filename:dirname(escript:script_name())++ "/src"),
    generate_files(Header, Module, Options);
main(_) ->
    io:format("ussage <nifty> <header> <module name> [<compiler options>~n").
